In [2]:
import requests, pandas as pd

In [3]:
url = (
        "https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=50&page=1&sparkline=false&price_change_percentage=1h,24h,7d"
    )
resp = requests.get(url, headers={"accept": "application/json"})
resp.raise_for_status()
data = resp.json()

In [4]:
# data

In [11]:
df = pd.DataFrame(data)

In [14]:
pd.json_normalize(data).head(5)

,id,symbol,name,image,current_price,market_cap,market_cap_rank,fully_diluted_valuation,total_volume,high_24h,...,atl_change_percentage,atl_date,roi,last_updated,price_change_percentage_1h_in_currency,price_change_percentage_24h_in_currency,price_change_percentage_7d_in_currency,roi.times,roi.currency,roi.percentage
0,bitcoin,btc,Bitcoin,https://coin-images.coingecko.com/coins/images...,116167.00,2310605477331,1,2310605477331,82276717740,119415.000,...,1.707126e+05,2013-07-06T00:00:00.000Z,NaN,2025-07-25T10:16:23.432Z,0.836564,-1.954871,-2.331224,NaN,NaN,NaN
1,ethereum,eth,Ethereum,https://coin-images.coingecko.com/coins/images...,3719.24,449489012157,2,449489012157,44466788242,3754.290,...,8.584730e+05,2015-10-20T00:00:00.000Z,NaN,2025-07-25T10:16:24.796Z,1.563887,2.146806,2.741505,41.802409,btc,4180.240896
2,ripple,xrp,XRP,https://coin-images.coingecko.com/coins/images...,3.13,185012577772,3,312268057700,8899776577,3.250,...,1.161529e+05,2014-05-22T00:00:00.000Z,NaN,2025-07-25T10:16:17.479Z,1.624257,0.621557,-9.459708,NaN,NaN,NaN
3,tether,usdt,Tether,https://coin-images.coingecko.com/coins/images...,1.00,162524978467,4,162524978467,175691610335,1.001,...,7.467292e+01,2015-03-02T00:00:00.000Z,NaN,2025-07-25T10:16:18.467Z,0.008060,-0.033409,-0.028628,NaN,NaN,NaN
4,binancecoin,bnb,BNB,https://coin-images.coingecko.com/coins/images...,771.81,107515571584,5,107515571584,2386315748,784.630,...,1.937559e+06,2017-10-19T00:00:00.000Z,NaN,2025-07-25T10:16:22.934Z,1.014899,0.810401,4.505881,NaN,NaN,NaN

In [31]:
url = f"https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=50&page=1&sparkline=false&price_change_percentage=1h,24h,7d"
resp = requests.get(url, headers={"accept": "application/json"})
resp.raise_for_status()
data = resp.json()

In [32]:
coin_df = pd.DataFrame(data)

In [37]:
for coin_id in coin_df['id']:
    pass

In [18]:
coin_id = "bitcoin"
vs_currency = "usd"
days = 5
url = f"https://api.coingecko.com/api/v3/coins/{coin_id}/market_chart?vs_currency={vs_currency}&days={days}"
resp = requests.get(url, headers={"accept": "application/json"})
resp.raise_for_status()
data = resp.json()

In [19]:
pd.DataFrame(data).head(10)

,prices,market_caps,total_volumes
0,"[1753009402200, 117950.02851116993]","[1753009402200, 2346609601029.03]","[1753009402200, 24410718461.63773]"
1,"[1753013029721, 117954.78788911905]","[1753013029721, 2346862785730.0063]","[1753013029721, 24493078307.00826]"
2,"[1753016640207, 118084.93847491883]","[1753016640207, 2348464912538.725]","[1753016640207, 26686467729.497128]"
3,"[1753020233333, 118329.057459225]","[1753020233333, 2353175458810.8516]","[1753020233333, 27183344544.171955]"
4,"[1753023838914, 118527.95095843298]","[1753023838914, 2358087907468.8525]","[1753023838914, 28149649165.85451]"
5,"[1753027441466, 118738.28818265932]","[1753027441466, 2362383575849.2036]","[1753027441466, 28429132693.731808]"
6,"[1753030888365, 118641.53460983634]","[1753030888365, 2360371076873.5356]","[1753030888365, 29124371771.969395]"
7,"[1753034610565, 118101.88737743786]","[1753034610565, 2349716988045.188]","[1753034610565, 29942488587.418995]"
8,"[1753038239563, 118407.70987859223]","[1753038239563, 2355944329101.397]","[1753038239563, 31398859660.511192]"
9,"[1753041674278, 118395.96713530371]","[1753041674278, 2355928090518.7856]","[1753041674278, 29919310268.650246]"

In [20]:
df_prices = pd.DataFrame(data["prices"], columns=["timestamp", "price"])
df_prices['timestamp'] = pd.to_datetime(df_prices['timestamp'], unit='ms')
df_prices.head()

                timestamp  price
0 2025-07-20 11:03:22.200 117950
1 2025-07-20 12:03:49.721 117955
2 2025-07-20 13:04:00.207 118085
3 2025-07-20 14:03:53.333 118329
4 2025-07-20 15:03:58.914 118528

In [21]:
pd.set_option('display.float_format', '{:.0f}'.format)

In [22]:
df_mcap = pd.DataFrame(data["market_caps"], columns=["timestamp", "market_cap"])
df_mcap['timestamp'] = pd.to_datetime(df_mcap['timestamp'], unit='ms')
df_mcap.head()

                timestamp    market_cap
0 2025-07-20 11:03:22.200 2346609601029
1 2025-07-20 12:03:49.721 2346862785730
2 2025-07-20 13:04:00.207 2348464912539
3 2025-07-20 14:03:53.333 2353175458811
4 2025-07-20 15:03:58.914 2358087907469

In [ ]:
df_vol = pd.DataFrame(data["total_volumes"], columns=["timestamp", "total_volumes"])
df_vol['timestamp'] = pd.to_datetime(df_vol['timestamp'], unit='ms')
df_vol.head()

                timestamp  total_volumes
0 2025-07-20 11:03:22.200    24410718462
1 2025-07-20 12:03:49.721    24493078307
2 2025-07-20 13:04:00.207    26686467729
3 2025-07-20 14:03:53.333    27183344544
4 2025-07-20 15:03:58.914    28149649166

In [38]:
df_merge = df_prices.merge(df_mcap,on='timestamp').merge(df_vol,on='timestamp')

In [39]:
df_merge['coin_id'] = coin_id

In [44]:
df_out = df_merge[["coin_id", "price", "market_cap", "total_volumes"]]

In [46]:
all_data = []

In [47]:
all_data.append(df_out)

In [48]:
all_data

[             coin_id  price    market_cap  total_volumes
 0    jito-staked-sol 117950 2346609601029    24410718462
 1    jito-staked-sol 117955 2346862785730    24493078307
 2    jito-staked-sol 118085 2348464912539    26686467729
 3    jito-staked-sol 118329 2353175458811    27183344544
 4    jito-staked-sol 118528 2358087907469    28149649166
 ..               ...    ...           ...            ...
 116  jito-staked-sol 115313 2294855153598    71986674359
 117  jito-staked-sol 115184 2288483709904    74811948694
 118  jito-staked-sol 115198 2292540454972    75042997368
 119  jito-staked-sol 115616 2300321308719    81588473468
 120  jito-staked-sol 116380 2315456257635    83102067232

 [121 rows x 4 columns]]

In [49]:
pd.concat(all_data)

             coin_id  price    market_cap  total_volumes
0    jito-staked-sol 117950 2346609601029    24410718462
1    jito-staked-sol 117955 2346862785730    24493078307
2    jito-staked-sol 118085 2348464912539    26686467729
3    jito-staked-sol 118329 2353175458811    27183344544
4    jito-staked-sol 118528 2358087907469    28149649166
..               ...    ...           ...            ...
116  jito-staked-sol 115313 2294855153598    71986674359
117  jito-staked-sol 115184 2288483709904    74811948694
118  jito-staked-sol 115198 2292540454972    75042997368
119  jito-staked-sol 115616 2300321308719    81588473468
120  jito-staked-sol 116380 2315456257635    83102067232

[121 rows x 4 columns]

In [80]:
import time

In [90]:
def get_coin_hist(coin_id, days):
    retry = 5
    for i in range(retry):
        vs_currency = "usd"
        url = f"https://api.coingecko.com/api/v3/coins/{coin_id}/market_chart?vs_currency={vs_currency}&days={days}"
        response = requests.get(url, headers={"accept": "application/json"})
        if response.status_code == 429:
            print(f"coin id: {coin_id}")
            print('Sleeping.....')
            time.sleep(20)
            continue
        return response
    

all_hist_data = []
for coin_id in coin_df['id']:
    response = get_coin_hist(coin_id=coin_id, days=5)
    coin_hist_data = response.json()
    df_prices = pd.DataFrame(coin_hist_data["prices"], columns=["timestamp", "price"])
    df_mcap = pd.DataFrame(coin_hist_data["market_caps"], columns=["timestamp", "market_cap"])
    df_vol = pd.DataFrame(coin_hist_data["total_volumes"], columns=["timestamp", "total_volumes"])
    df_merge = df_prices.merge(df_mcap,on='timestamp').merge(df_vol,on='timestamp')
    df_merge['timestamp'] = pd.to_datetime(df_merge['timestamp'], unit='ms')
    df_merge['coin_id'] = coin_id
    all_hist_data.append(df_merge[["coin_id","price","market_cap","total_volumes"]])

coin id: usd-coin
Sleeping.....
coin id: usd-coin
Sleeping.....
coin id: usd-coin
Sleeping.....
coin id: tron
Sleeping.....
coin id: tron
Sleeping.....
coin id: tron
Sleeping.....
coin id: wrapped-steth
Sleeping.....
coin id: wrapped-steth
Sleeping.....
coin id: wrapped-steth
Sleeping.....
coin id: sui
Sleeping.....
coin id: sui
Sleeping.....
coin id: sui
Sleeping.....
coin id: bitcoin-cash
Sleeping.....
coin id: bitcoin-cash
Sleeping.....
coin id: bitcoin-cash
Sleeping.....
coin id: avalanche-2
Sleeping.....
coin id: avalanche-2
Sleeping.....
coin id: avalanche-2
Sleeping.....
coin id: weth
Sleeping.....
coin id: weth
Sleeping.....
coin id: weth
Sleeping.....
coin id: ethena-usde
Sleeping.....
coin id: ethena-usde
Sleeping.....
coin id: ethena-usde
Sleeping.....
coin id: whitebit
Sleeping.....
coin id: whitebit
Sleeping.....
coin id: whitebit
Sleeping.....
coin id: bitget-token
Sleeping.....
coin id: bitget-token
Sleeping.....
coin id: bitget-token
Sleeping.....
coin id: ethena-staked-usde
Sleeping.....
coin id: ethena-staked-usde
Sleeping.....
coin id: ethena-staked-usde
Sleeping.....
coin id: ethereum-classic
Sleeping.....
coin id: ethereum-classic
Sleeping.....
coin id: ethereum-classic
Sleeping.....

KeyboardInterrupt: